#!/bin/bash

# Affectation des variables et fonction communes
. /etc/profile
. $GRANDMAHOME/cfg/grandma.cfg

# Creation des repertoires temporaires et des timestamps
$GRANDMAHOME/lib/creation_rep_travail.sh ; if [ $? -ne 0 ]; then UNKNOWN "KO : Probleme lors de la creation des repertoires temporaires"; fi

# Bridage des scenarios en cas de surcharge de la sonde
$GRANDMAHOME/lib/controle_surcharge.sh ; if [ $? -ne 0 ]; then UNKNOWN "KO : La sonde $nomsonde est surchargee, l'execution des scenarios est bridee" ; fi

# Controle des plages horaires et jours d'execution
$GRANDMAHOME/lib/verif_heure_exception.sh FTN $1 ; if [ $? -eq 1 ]; then OKOUT "OK : pas de contrôle a faire sur cette periode"; fi

# Recuperation des mots de passe
source $GRANDMAHOME/lib/gestion_motdepasse.sh 123456 ; if [ $? -eq 3 ]; then UNKNOWN "KO : Probleme lors de la recuperation des mots de passe"; fi

# Test de la page d'accueil
$curl $curl_opts "http://www.toto.fr/" > $tmpdir/page.html 2>&1
TESTRET ; COUNT "Bourse avec votre courtier en ligne Toto"
if [ "$count" -ne 2 ];then FATAL "KO : Pas de page d'accueil"; fi

# Test de la chaine Appel payant depuis un poste fixe
$curl $curl_opts "http://www.toto.fr/bourse/welcome.jsp" > $tmpdir/page.html 2>&1
TESTRET ; COUNT "Appel payant depuis un poste fixe"
if [ "$count" -ne 1 ];then FATAL "KO : Pas de chaine Appel payant depuis un poste fixe"; fi

# on clic sur Acces client
$curl $curl_opts "https://www.toto.fr/fr/whoami.jsp" > $tmpdir/page.html 2>&1
TESTRET ; COUNT "Identifiant"
if [ "$count" -ne 2 ];then FATAL "KO : Les 2 chaines -Identifiant- n'apparaissent pas"; fi

# Identification avec :
$curl $curl_opts "https://www.toto.fr/checkacces" -d "locale=fr&login=123456&passwd=$motdepasse" -c $tmpdir/cookies -b $tmpdir/cookies 1> $tmpdir/page.html 2>&1
TESTRET ; COUNT "018765643543 (COMPTE TEST)"
if [ "$count" -ne 1 ];then FATAL "KO : Impossible d'afficher la page de synthese des comptes 1"; fi
$curl $curl_opts "https://www.toto.fr/fr/mes-comptes/synthese-tous-comptes.jsp" -b $tmpdir/cookies > $tmpdir/page.html 2>&1
TESTRET ; COUNT "SYNTHESE DES COMPTES"
if [ "$count" -ne 1 ];then FATAL "KO : Impossible d'afficher la page de synthese des comptes 2"; fi

OK "OK : Scenario TOTO Generaliste nominal"
